### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ZhouZoey** [JerryX1110/RPCMVOS#1]
Excuse me!  Can you  provide pre training weight files:  resnet101-deeplabv3p.pth.tar

**Comment by JerryX1110** [comment]
OK. resnet101-deeplabv3p:<https://drive.google.com/file/d/1H3yUShfPqzxSt-nHJP-zYSbbu2o_RQQu/view>

**Comment by ZhouZoey** [comment]
Thank you!
