### ISSUE TITLE
About correctly loading in pretraining backbone

### ISSUE THREAD

**Issue by Student204161** [JerryX1110/RPCMVOS#11]
Hi there,

I am unsure if I loaded in the ResNet backbone properly. My output log returns:

```
Remove ['backbone.bn1.num_batches_tracked', 'backbone.layer1.0.bn1.num_batches_tracked', 'backbone.layer1.0.bn2.num_batches_tracked',...]     
Load pretrained backbone model from /work3/s204161/BachelorData/vos_data/resnet101-deeplabv3p.pth.tar.
Start training.
Itr:0, LR:0.0000100, Time:213.254, Obj:1.4, S0: L 1.989(1.989) IoU 0.211(0.211), S1: L 2.101(2.101) IoU 0.192(0.192), S2: L 2.097(2.097) IoU 0.180(0.180)
....
```
I am not sure what remove backbone.bn1.num_batches_tracked means and I'm worried that it is checking that something is not in order and thus removing the pretrained backbone entirely. The whole list that it removes is listed further down below.

Thanks for your work

`Remove ['backbone.bn1.num_batches_tracked', 'backbone.layer1.0.bn1.num_batches_tracked', 'backbone.layer1.0.bn2.num_batches_tracked', 'backbone.layer1.0.bn3.num_batches_tracked', 'backbone.layer1.0.downsample.1.num_batches_tracked', 'backbone.layer1.1.bn1.num_batches_tracked', 'backbone.layer1.1.bn2.num_batches_tracked', 'backbone.layer1.1.bn3.num_batches_tracked', 'backbone.layer1.2.bn1.num_batches_tracked', 'backbone.layer1.2.bn2.num_batches_tracked', 'backbone.layer1.2.bn3.num_batches_tracked', 'backbone.layer2.0.bn1.num_batches_tracked', 'backbone.layer2.0.bn2.num_batches_tracked', 'backbone.layer2.0.bn3.num_batches_tracked', 'backbone.layer2.0.downsample.1.num_batches_tracked', 'backbone.layer2.1.bn1.num_batches_tracked', 'backbone.layer2.1.bn2.num_batches_tracked', 'backbone.layer2.1.bn3.num_batches_tracked', 'backbone.layer2.2.bn1.num_batches_tracked', 'backbone.layer2.2.bn2.num_batches_tracked', 'backbone.layer2.2.bn3.num_batches_tracked', 'backbone.layer2.3.bn1.num_batches_tracked', 'backbone.layer2.3.bn2.num_batches_tracked', 'backbone.layer2.3.bn3.num_batches_tracked', 'backbone.layer3.0.bn1.num_batches_tracked', 'backbone.layer3.0.bn2.num_batches_tracked', 'backbone.layer3.0.bn3.num_batches_tracked', 'backbone.layer3.0.downsample.1.num_batches_tracked', 'backbone.layer3.1.bn1.num_batches_tracked', 'backbone.layer3.1.bn2.num_batches_tracked', 'backbone.layer3.1.bn3.num_batches_tracked', 'backbone.layer3.2.bn1.num_batches_tracked', 'backbone.layer3.2.bn2.num_batches_tracked', 'backbone.layer3.2.bn3.num_batches_tracked', 'backbone.layer3.3.bn1.num_batches_tracked', 'backbone.layer3.3.bn2.num_batches_tracked', 'backbone.layer3.3.bn3.num_batches_tracked', 'backbone.layer3.4.bn1.num_batches_tracked', 'backbone.layer3.4.bn2.num_batches_tracked', 'backbone.layer3.4.bn3.num_batches_tracked', 'backbone.layer3.5.bn1.num_batches_tracked', 'backbone.layer3.5.bn2.num_batches_tracked', 'backbone.layer3.5.bn3.num_batches_tracked', 'backbone.layer3.6.bn1.num_batches_tracked', 'backbone.layer3.6.bn2.num_batches_tracked', 'backbone.layer3.6.bn3.num_batches_tracked', 'backbone.layer3.7.bn1.num_batches_tracked', 'backbone.layer3.7.bn2.num_batches_tracked', 'backbone.layer3.7.bn3.num_batches_tracked', 'backbone.layer3.8.bn1.num_batches_tracked', 'backbone.layer3.8.bn2.num_batches_tracked', 'backbone.layer3.8.bn3.num_batches_tracked', 'backbone.layer3.9.bn1.num_batches_tracked', 'backbone.layer3.9.bn2.num_batches_tracked', 'backbone.layer3.9.bn3.num_batches_tracked', 'backbone.layer3.10.bn1.num_batches_tracked', 'backbone.layer3.10.bn2.num_batches_tracked', 'backbone.layer3.10.bn3.num_batches_tracked', 'backbone.layer3.11.bn1.num_batches_tracked', 'backbone.layer3.11.bn2.num_batches_tracked', 'backbone.layer3.11.bn3.num_batches_tracked', 'backbone.layer3.12.bn1.num_batches_tracked', 'backbone.layer3.12.bn2.num_batches_tracked', 'backbone.layer3.12.bn3.num_batches_tracked', 'backbone.layer3.13.bn1.num_batches_tracked', 'backbone.layer3.13.bn2.num_batches_tracked', 'backbone.layer3.13.bn3.num_batches_tracked', 'backbone.layer3.14.bn1.num_batches_tracked', 'backbone.layer3.14.bn2.num_batches_tracked', 'backbone.layer3.14.bn3.num_batches_tracked', 'backbone.layer3.15.bn1.num_batches_tracked', 'backbone.layer3.15.bn2.num_batches_tracked', 'backbone.layer3.15.bn3.num_batches_tracked', 'backbone.layer3.16.bn1.num_batches_tracked', 'backbone.layer3.16.bn2.num_batches_tracked', 'backbone.layer3.16.bn3.num_batches_tracked', 'backbone.layer3.17.bn1.num_batches_tracked', 'backbone.layer3.17.bn2.num_batches_tracked', 'backbone.layer3.17.bn3.num_batches_tracked', 'backbone.layer3.18.bn1.num_batches_tracked', 'backbone.layer3.18.bn2.num_batches_tracked', 'backbone.layer3.18.bn3.num_batches_tracked', 'backbone.layer3.19.bn1.num_batches_tracked', 'backbone.layer3.19.bn2.num_batches_tracked', 'backbone.layer3.19.bn3.num_batches_tracked', 'backbone.layer3.20.bn1.num_batches_tracked', 'backbone.layer3.20.bn2.num_batches_tracked', 'backbone.layer3.20.bn3.num_batches_tracked', 'backbone.layer3.21.bn1.num_batches_tracked', 'backbone.layer3.21.bn2.num_batches_tracked', 'backbone.layer3.21.bn3.num_batches_tracked', 'backbone.layer3.22.bn1.num_batches_tracked', 'backbone.layer3.22.bn2.num_batches_tracked', 'backbone.layer3.22.bn3.num_batches_tracked', 'backbone.layer4.0.bn1.num_batches_tracked', 'backbone.layer4.0.bn2.num_batches_tracked', 'backbone.layer4.0.bn3.num_batches_tracked', 'backbone.layer4.0.downsample.1.num_batches_tracked', 'backbone.layer4.1.bn1.num_batches_tracked', 'backbone.layer4.1.bn2.num_batches_tracked', 'backbone.layer4.1.bn3.num_batches_tracked', 'backbone.layer4.2.bn1.num_batches_tracked', 'backbone.layer4.2.bn2.num_batches_tracked', 'backbone.layer4.2.bn3.num_batches_tracked', 'aspp.aspp1.bn.num_batches_tracked', 'aspp.aspp2.bn.num_batches_tracked', 'aspp.aspp3.bn.num_batches_tracked', 'aspp.aspp4.bn.num_batches_tracked', 'aspp.global_avg_pool.2.num_batches_tracked', 'aspp.bn1.num_batches_tracked', 'decoder.bn1.num_batches_tracked', 'decoder.last_conv.1.num_batches_tracked', 'decoder.last_conv.5.num_batches_tracked', 'decoder.last_last_conv.weight', 'decoder.last_last_conv.bias'] from pretrained model.
`

**Comment by JerryX1110** [comment]
Hi! It seems that there is something wrong with the pretrained ckpt for backbone. You can have a try of the ckpt that I recently updated in the README page. Hopefully it can resolve your problem.





---Original---
From: ***@***.***&gt;
Date: Mon, Apr 3, 2023 19:43 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [JerryX1110/RPCMVOS] Correctly loading in pretraining backbone (Issue#11)




 
Hi there,
 
I am unsure if I loaded in the ResNet backbone properly. My output log returns:
 Remove ['backbone.bn1.num_batches_tracked', 'backbone.layer1.0.bn1.num_batches_tracked', 'backbone.layer1.0.bn2.num_batches_tracked',...]      Load pretrained backbone model from /work3/s204161/BachelorData/vos_data/resnet101-deeplabv3p.pth.tar. Start training. Itr:0, LR:0.0000100, Time:213.254, Obj:1.4, S0: L 1.989(1.989) IoU 0.211(0.211), S1: L 2.101(2.101) IoU 0.192(0.192), S2: L 2.097(2.097) IoU 0.180(0.180) ....  
I am not sure what remove backbone.bn1.num_batches_tracked means and I'm worried that it is checking that something is not in order and thus removing the pretrained backbone entirely. The whole list that it removes is listed further down below.
 
Thanks for your work,
 
Sincerely Khalil
 
Remove ['backbone.bn1.num_batches_tracked', 'backbone.layer1.0.bn1.num_batches_tracked', 'backbone.layer1.0.bn2.num_batches_tracked', 'backbone.layer1.0.bn3.num_batches_tracked', 'backbone.layer1.0.downsample.1.num_batches_tracked', 'backbone.layer1.1.bn1.num_batches_tracked', 'backbone.layer1.1.bn2.num_batches_tracked', 'backbone.layer1.1.bn3.num_batches_tracked', 'backbone.layer1.2.bn1.num_batches_tracked', 'backbone.layer1.2.bn2.num_batches_tracked', 'backbone.layer1.2.bn3.num_batches_tracked', 'backbone.layer2.0.bn1.num_batches_tracked', 'backbone.layer2.0.bn2.num_batches_tracked', 'backbone.layer2.0.bn3.num_batches_tracked', 'backbone.layer2.0.downsample.1.num_batches_tracked', 'backbone.layer2.1.bn1.num_batches_tracked', 'backbone.layer2.1.bn2.num_batches_tracked', 'backbone.layer2.1.bn3.num_batches_tracked', 'backbone.layer2.2.bn1.num_batches_tracked', 'backbone.layer2.2.bn2.num_batches_tracked', 'backbone.layer2.2.bn3.num_batches_tracked', 'backbone.layer2.3.bn1.num_batches_tracked', 'backbone.layer2.3.bn2.num_batches_tracked', 'backbone.layer2.3.bn3.num_batches_tracked', 'backbone.layer3.0.bn1.num_batches_tracked', 'backbone.layer3.0.bn2.num_batches_tracked', 'backbone.layer3.0.bn3.num_batches_tracked', 'backbone.layer3.0.downsample.1.num_batches_tracked', 'backbone.layer3.1.bn1.num_batches_tracked', 'backbone.layer3.1.bn2.num_batches_tracked', 'backbone.layer3.1.bn3.num_batches_tracked', 'backbone.layer3.2.bn1.num_batches_tracked', 'backbone.layer3.2.bn2.num_batches_tracked', 'backbone.layer3.2.bn3.num_batches_tracked', 'backbone.layer3.3.bn1.num_batches_tracked', 'backbone.layer3.3.bn2.num_batches_tracked', 'backbone.layer3.3.bn3.num_batches_tracked', 'backbone.layer3.4.bn1.num_batches_tracked', 'backbone.layer3.4.bn2.num_batches_tracked', 'backbone.layer3.4.bn3.num_batches_tracked', 'backbone.layer3.5.bn1.num_batches_tracked', 'backbone.layer3.5.bn2.num_batches_tracked', 'backbone.layer3.5.bn3.num_batches_tracked', 'backbone.layer3.6.bn1.num_batches_tracked', 'backbone.layer3.6.bn2.num_batches_tracked', 'backbone.layer3.6.bn3.num_batches_tracked', 'backbone.layer3.7.bn1.num_batches_tracked', 'backbone.layer3.7.bn2.num_batches_tracked', 'backbone.layer3.7.bn3.num_batches_tracked', 'backbone.layer3.8.bn1.num_batches_tracked', 'backbone.layer3.8.bn2.num_batches_tracked', 'backbone.layer3.8.bn3.num_batches_tracked', 'backbone.layer3.9.bn1.num_batches_tracked', 'backbone.layer3.9.bn2.num_batches_tracked', 'backbone.layer3.9.bn3.num_batches_tracked', 'backbone.layer3.10.bn1.num_batches_tracked', 'backbone.layer3.10.bn2.num_batches_tracked', 'backbone.layer3.10.bn3.num_batches_tracked', 'backbone.layer3.11.bn1.num_batches_tracked', 'backbone.layer3.11.bn2.num_batches_tracked', 'backbone.layer3.11.bn3.num_batches_tracked', 'backbone.layer3.12.bn1.num_batches_tracked', 'backbone.layer3.12.bn2.num_batches_tracked', 'backbone.layer3.12.bn3.num_batches_tracked', 'backbone.layer3.13.bn1.num_batches_tracked', 'backbone.layer3.13.bn2.num_batches_tracked', 'backbone.layer3.13.bn3.num_batches_tracked', 'backbone.layer3.14.bn1.num_batches_tracked', 'backbone.layer3.14.bn2.num_batches_tracked', 'backbone.layer3.14.bn3.num_batches_tracked', 'backbone.layer3.15.bn1.num_batches_tracked', 'backbone.layer3.15.bn2.num_batches_tracked', 'backbone.layer3.15.bn3.num_batches_tracked', 'backbone.layer3.16.bn1.num_batches_tracked', 'backbone.layer3.16.bn2.num_batches_tracked', 'backbone.layer3.16.bn3.num_batches_tracked', 'backbone.layer3.17.bn1.num_batches_tracked', 'backbone.layer3.17.bn2.num_batches_tracked', 'backbone.layer3.17.bn3.num_batches_tracked', 'backbone.layer3.18.bn1.num_batches_tracked', 'backbone.layer3.18.bn2.num_batches_tracked', 'backbone.layer3.18.bn3.num_batches_tracked', 'backbone.layer3.19.bn1.num_batches_tracked', 'backbone.layer3.19.bn2.num_batches_tracked', 'backbone.layer3.19.bn3.num_batches_tracked', 'backbone.layer3.20.bn1.num_batches_tracked', 'backbone.layer3.20.bn2.num_batches_tracked', 'backbone.layer3.20.bn3.num_batches_tracked', 'backbone.layer3.21.bn1.num_batches_tracked', 'backbone.layer3.21.bn2.num_batches_tracked', 'backbone.layer3.21.bn3.num_batches_tracked', 'backbone.layer3.22.bn1.num_batches_tracked', 'backbone.layer3.22.bn2.num_batches_tracked', 'backbone.layer3.22.bn3.num_batches_tracked', 'backbone.layer4.0.bn1.num_batches_tracked', 'backbone.layer4.0.bn2.num_batches_tracked', 'backbone.layer4.0.bn3.num_batches_tracked', 'backbone.layer4.0.downsample.1.num_batches_tracked', 'backbone.layer4.1.bn1.num_batches_tracked', 'backbone.layer4.1.bn2.num_batches_tracked', 'backbone.layer4.1.bn3.num_batches_tracked', 'backbone.layer4.2.bn1.num_batches_tracked', 'backbone.layer4.2.bn2.num_batches_tracked', 'backbone.layer4.2.bn3.num_batches_tracked', 'aspp.aspp1.bn.num_batches_tracked', 'aspp.aspp2.bn.num_batches_tracked', 'aspp.aspp3.bn.num_batches_tracked', 'aspp.aspp4.bn.num_batches_tracked', 'aspp.global_avg_pool.2.num_batches_tracked', 'aspp.bn1.num_batches_tracked', 'decoder.bn1.num_batches_tracked', 'decoder.last_conv.1.num_batches_tracked', 'decoder.last_conv.5.num_batches_tracked', 'decoder.last_last_conv.weight', 'decoder.last_last_conv.bias'] from pretrained model.

**Comment by Student204161** [comment]
Thanks for the quick answer. I'll have a go at it tomorrow and hopefully it will work.

**Comment by Student204161** [comment]
Sorry for the late answer. It seems like I already was using the updated ckpt file - I get the exact same output as before.

I am not supposed to unzip the tar file, right? because when i write tar -xf /path/to/checkpoint/resnetweights.pth.tar I get unpacking errors.

Thanks,

The config file:
```

import torch
import argparse
import os
import sys
import cv2
import time
import socket
import random

class Configuration():
    def __init__(self):
        self.EXP_NAME = 'resnet101_rpcm_ytb/'

        self.EVAL_AUTO_RESUME = False
        self.UNC_RATIO = 1.0
        self.MEM_EVERY = 5
        self.USE_SF = False
        self.PAST_FRAME_NUM = 4
        self.COMPRESSION_RATE = 4
        self.BLOCK_NUM = 2

        self.DIR_ROOT = '/work3/s204161/BachelorData/vos_data/datasets/'  ## your custom dataset path
        self.DIR_DAVIS =  os.path.join(self.DIR_ROOT, 'DAVIS') ## davis dataset path
        self.DIR_YTB =  os.path.join(self.DIR_ROOT, 'YouTube/train/') ## ytb19 dataset path (for training)
        self.DIR_YTB_EVAL18 =  os.path.join(self.DIR_ROOT, 'YouTube2018/valid/') ## ytb18 dataset path (for evaluation)
        self.DIR_YTB_EVAL19 =  os.path.join(self.DIR_ROOT,'YouTube/valid/')   ## ytb18 dataset path (for evaluation)
        self.DIR_RESULT = os.path.join(self.DIR_ROOT, 'result', self.EXP_NAME)  ## result saving path
        self.DIR_CUSTOM_TEST_IMAGES = os.path.join(self.DIR_ROOT,'custom_test/test/JPEGImages/') #for custom data eval
        self.DIR_CUSTOM_TEST_LABELS = os.path.join(self.DIR_ROOT,'custom_test/test/Annotations/') 
        self.DIR_CUSTOM_EVAL = os.path.join(self.DIR_ROOT,'custom_test/test/') 

        self.DIR_CKPT = os.path.join(self.DIR_RESULT, 'ckpt')
        self.DIR_LOG = os.path.join(self.DIR_RESULT, 'log')
        self.DIR_IMG_LOG = os.path.join(self.DIR_RESULT, 'log', 'img')
        self.DIR_TB_LOG = os.path.join(self.DIR_RESULT, 'log', 'tensorboard')
        self.DIR_EVALUATION = os.path.join(self.DIR_RESULT, 'eval')

        self.DATASETS = ['youtubevos']
        self.DATA_WORKERS = 16
        self.DATA_RANDOMCROP = (465, 465)
        self.DATA_RANDOMFLIP = 0.5
        self.DATA_MAX_CROP_STEPS = 5
        self.DATA_MIN_SCALE_FACTOR = 1.
        self.DATA_MAX_SCALE_FACTOR = 1.3
        self.DATA_SHORT_EDGE_LEN = 480
        self.DATA_RANDOM_REVERSE_SEQ = True
        self.DATA_DAVIS_REPEAT = 30
        self.DATA_CURR_SEQ_LEN = 3
        self.DATA_RANDOM_GAP_DAVIS = 3
        self.DATA_RANDOM_GAP_YTB = 3


        self.PRETRAIN = True # False #True # True #True
        self.PRETRAIN_FULL = False #True #True
        self.PRETRAIN_MODEL = '/work3/s204161/BachelorData/resnet101-deeplabv3p.pth.tar'  #/work3/s204161/BachelorData/vos_data/datasets/result/resnet101_rpcm_ytb/ckpt/save_step_25000.pth' 

        self.MODEL_BACKBONE = 'resnet'
        self.MODEL_MODULE = 'networks.rpcm.rpcm'
        self.MODEL_OUTPUT_STRIDE = 16
        self.MODEL_ASPP_OUTDIM = 256
        self.MODEL_SHORTCUT_DIM = 48
        self.MODEL_SEMANTIC_EMBEDDING_DIM = 100
        self.MODEL_HEAD_EMBEDDING_DIM = 256
        self.MODEL_PRE_HEAD_EMBEDDING_DIM = 64
        self.MODEL_GN_GROUPS = 32
        self.MODEL_GN_EMB_GROUPS = 25
        self.MODEL_MULTI_LOCAL_DISTANCE = [2, 4, 6, 8, 10, 12]
        self.MODEL_LOCAL_DOWNSAMPLE = True
        self.MODEL_REFINE_CHANNELS = 64  # n * 32
        self.MODEL_LOW_LEVEL_INPLANES = 256 if self.MODEL_BACKBONE == 'resnet' else 24
        self.MODEL_RELATED_CHANNELS = 64
        self.MODEL_EPSILON = 1e-5
        self.MODEL_MATCHING_BACKGROUND = True
        self.MODEL_GCT_BETA_WD = True
        self.MODEL_FLOAT16_MATCHING = False
        self.MODEL_FREEZE_BN = True
        self.MODEL_FREEZE_BACKBONE = False

        self.TRAIN_TOTAL_STEPS = 37500
        self.TRAIN_START_STEP = 0
        self.TRAIN_LR = 0.02
        self.TRAIN_MOMENTUM = 0.9
        self.TRAIN_COSINE_DECAY = False
        self.TRAIN_WARM_UP_STEPS = 100
        self.TRAIN_WEIGHT_DECAY = 15e-5
        self.TRAIN_POWER = 0.9
        self.TRAIN_GPUS = 1
        self.TRAIN_BATCH_SIZE = 16
        self.TRAIN_START_SEQ_TRAINING_STEPS = self.TRAIN_TOTAL_STEPS / 2
        self.TRAIN_TBLOG = False
        self.TRAIN_TBLOG_STEP = 60
        self.TRAIN_LOG_STEP = 50
        self.TRAIN_IMG_LOG = False
        self.TRAIN_TOP_K_PERCENT_PIXELS = 0.15
        self.TRAIN_HARD_MINING_STEP = self.TRAIN_TOTAL_STEPS / 2
        self.TRAIN_CLIP_GRAD_NORM = 5.
        self.TRAIN_SAVE_STEP = 2500
        self.TRAIN_MAX_KEEP_CKPT = 16
        self.TRAIN_RESUME = True
        self.TRAIN_RESUME_CKPT = None
        self.TRAIN_RESUME_STEP = 0
        self.TRAIN_AUTO_RESUME = True
        self.TRAIN_GLOBAL_ATROUS_RATE = 1
        self.TRAIN_LOCAL_ATROUS_RATE = 1
        self.TRAIN_LOCAL_PARALLEL = True
        self.TRAIN_GLOBAL_CHUNKS = 1
        self.TRAIN_DATASET_FULL_RESOLUTION = True


        self.TEST_GPU_ID = 0
        self.TEST_DATASET = 'custom_test'
        self.TEST_DATASET_FULL_RESOLUTION = False
        self.TEST_DATASET_SPLIT = ['test']
        self.TEST_CKPT_PATH = None
        self.TEST_CKPT_STEP = None  # if "None", evaluate the latest checkpoint.
        self.TEST_FLIP = False
        self.TEST_MULTISCALE = [1]
        self.TEST_MIN_SIZE = None
        self.TEST_MAX_SIZE = 800 * 1.3 if self.TEST_MULTISCALE == [1.] else 800
        self.TEST_WORKERS = 1
        self.TEST_GLOBAL_CHUNKS = 1
        self.TEST_GLOBAL_ATROUS_RATE = 1
        self.TEST_LOCAL_ATROUS_RATE = 1
        self.TEST_LOCAL_PARALLEL = True

        # dist
        self.DIST_ENABLE = True
        self.DIST_BACKEND = "nccl"

        myname = socket.getfqdn(socket.gethostname(  ))
        myaddr = socket.gethostbyname(myname)

        self.DIST_URL = "tcp://"+myaddr+":"+str(random.randint(30000,50000))
        self.DIST_START_GPU = 0

        self.__check()

    def __check(self):
        if not torch.cuda.is_available():
                raise ValueError('config.py: cuda is not avalable')
        if self.TRAIN_GPUS == 0:
                raise ValueError('config.py: the number of GPU is 0')
        for path in [self.DIR_RESULT, self.DIR_CKPT, self.DIR_LOG, self.DIR_EVALUATION, self.DIR_IMG_LOG, self.DIR_TB_LOG]:
            if not os.path.isdir(path):
                os.makedirs(path)



cfg = Configuration()
```

**Comment by JerryX1110** [comment]
Yeah, you do not need to un-tar the file.   

`self.PRETRAIN_MODEL = '/work3/s204161/BachelorData/resnet101-deeplabv3p.pth.tar'` in your config should be right.

**Comment by Student204161** [comment]
Hi, 

Hope everyone had a good Easter. Just wanted to do an update to share my solution in case someone ran into the same problem as me.

I solved my problem by renaming the layers, so that the prefix 'feature_extracter.' was added. This seemingly solves my problem, since now only a long list of empty tensors are removed with the exception of 'feature_extracter.decoder.last_last_conv.bias'.

The empty tensors look like:
'feature_extracter.backbone.X.bnY.num_batches_tracked' (where X is some layer, e.g. layer1, and Y an integer) & they have no size --> empty.

The script:

```
import torch
from collections import OrderedDict

path = '/work3/s204161/BachelorData/vos_data/resnet101-deeplabv3p.pth.tar'
new_path = '/work3/s204161/BachelorData/vos_data/renamed_resnet101-deeplabv3p.pth.tar'

checkpoint = torch.load(path, map_location='cpu')
weights = checkpoint['state_dict']
renamed_weights = OrderedDict()

for items in weights:
   renamed_weights['feature_extracter.'+items] = renamed_weights[items]

torch.save({'state_dict': renamed_weights}, new_path)

```

**Comment by JerryX1110** [comment]
Thanks for your sharing！



---Original---
From: ***@***.***&gt;
Date: Thu, Apr 13, 2023 00:14 AM
To: ***@***.***&gt;;
Cc: "Xiaohao ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [JerryX1110/RPCMVOS] About correctly loading in pretrainingbackbone (Issue #11)




 
Hi,
 
Hope everyone had a good Easter. Just wanted to do an update to share my solution in case someone ran into the same problem as me.
 
I solved my problem by renaming the layers, so that the prefix 'feature_extracter.' was added. This seemingly solves my problem, since now only a long list of empty tensors are removed with the exception of 'feature_extracter.decoder.last_last_conv.bias'.
 
The empty tensors look like:
 'feature_extracter.backbone.X.bnY.num_batches_tracked' (where X is some layer, e.g. layer1, and Y an integer) &amp; they have no size --&gt; empty.
 
The script:
 import torch from collections import OrderedDict path = '/work3/s204161/BachelorData/vos_data/resnet101-deeplabv3p.pth.tar' new_path = '/work3/s204161/BachelorData/vos_data/renamed_resnet101-deeplabv3p.pth.tar' checkpoint = torch.load(path, map_location='cpu') weights = checkpoint['state_dict'] renamed_weights = OrderedDict() for items in weights:    renamed_weights['feature_extracter.'+items] = renamed_weights[items] torch.save({'state_dict': renamed_weights}, new_path)
