### ISSUE TITLE
about the code implementation of distance calculation for matching

### ISSUE THREAD

**Issue by harrytea** [JerryX1110/RPCMVOS#12]
hi, xiaohao,

Good work! 
I am a master student at USTC, and i have some confusion about the code implementation, e.g., in matching.py, line 196, the distance is calculated with "(torch.sigmoid(nn_features_reshape + dis_bias.view(1, 1, 1, -1, 1)) - 0.5) * 2", according to the original paper, it should be  "(0.5-torch.sigmoid(-(nn_features_reshape + dis_bias.view(1, 1, 1, -1, 1)))) * 2", why?
This is my email, wyh1998@mail.ustc.edu.cn. Can you share me your wechat id, and i have some questions for advice.

Thanks~

**Comment by JerryX1110** [comment]
Hi Yonghui,

Thanks for your interest in our work.

For  the distance calculation method, the two formulations ("(torch.sigmoid(nn_features_reshape + dis_bias.view(1, 1, 1, -1, 1)) - 0.5) * 2" and "(0.5-torch.sigmoid(-(nn_features_reshape + dis_bias.view(1, 1, 1, -1, 1)))) * 2") are actually equivalent as nn_features_reshape and dis_bias are both learnable embeddings.

I think it would be better if you raise your questions in this repo. I am willing to have discussions on VOS. : )

**Comment by harrytea** [comment]
> Hi Yonghui,
> 
> Thanks for your interest in our work.
> 
> For the distance calculation method, the two formulations ("(torch.sigmoid(nn_features_reshape + dis_bias.view(1, 1, 1, -1, 1)) - 0.5) * 2" and "(0.5-torch.sigmoid(-(nn_features_reshape + dis_bias.view(1, 1, 1, -1, 1)))) * 2") are actually equivalent as nn_features_reshape and dis_bias are both learnable embeddings.
> 
> I think it would be better if you raise your questions in this repo. I am willing to have discussions on VOS. : )

I know, thanks~
In the scripts/ytb_eval_with_RPA.sh file, for the first line, the "configs.resnet101_p2t" is missing, where can i get it?

**Comment by JerryX1110** [comment]
Thanks for your correction. It should be "configs.resnet101_rpcm_ytb_stage_1"
