### ISSUE TITLE
about  Shannon entropy

### ISSUE THREAD

**Issue by lsy-dot** [JerryX1110/RPCMVOS#6]
I'm so sorry to bother you, I recently read your masterpiece. I am very interested in the calculation method in the formula for calculating information entropy in the Prediction reliability part of your paper. I would like to ask how the probability represented by the symbol P of the formula is calculated.
![image](https://user-images.githubusercontent.com/32125615/178098154-43dbb403-0580-4bab-8b59-4a54f35ec3d7.png)

**Comment by JerryX1110** [comment]
Thanks for your interest on our work! 

Actually, the capitalized P denotes a probability function, which is an identity function in our final implementation and can be omitted. Meanwhile, the formula inside the P() is a softmax function which is calculated among various object-specific layers in a certain pixel-grid position.

Sorry for the confusion brought by the notation! We would clarify it in the next arxiv revision! Thanks!

Welcome to further questions and discussions!
