### ISSUE TITLE
How Can I setup dataset and .pth path?

### ISSUE THREAD

**Issue by kkk3449** [JerryX1110/RPCMVOS#8]
I git clone this git page and download datasets and .pth file suessful, and then I want to know how to setup dataset and pth path.
I got a path error.

![Screenshot from 2022-08-19 17-17-58](https://user-images.githubusercontent.com/60597598/185576020-50d0b6ae-ada4-4d42-ab46-1cfe33c94529.png)

**Comment by JerryX1110** [comment]
You need to modify the dataset loading path and the .pth loading path in the https://github.com/JerryX1110/RPCMVOS/blob/main/configs/resnet101_rpcm_ytb_stage_1.py and https://github.com/JerryX1110/RPCMVOS/blob/main/configs/resnet101_rpcm_ytb_stage_2.py.

I add some descriptions about the dataset path configs in these two config files. If you still have problems, please do not hesitate to let me know~ : )

**Comment by kkk3449** [comment]
> You need to modify the dataset loading path and the .pth loading path in the https://github.com/JerryX1110/RPCMVOS/blob/main/configs/resnet101_rpcm_ytb_stage_1.py and https://github.com/JerryX1110/RPCMVOS/blob/main/configs/resnet101_rpcm_ytb_stage_2.py.
> 
> I add some descriptions about the dataset path configs in these two config files. If you still have problems, please do not hesitate to let me know~ : )

Thanks, I will try it!
